# Generated by Django 2.2.2 on 2019-07-06 01:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('VolleyUp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.CharField(max_length=32, null=True, verbose_name='Podaj passcode'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.IntegerField(choices=[(1, 'PZU'), (2, 'Siemens'), (3, 'Wedel'), (4, 'PJATK'), (5, 'Volley Up')], default=5, null=True, verbose_name='Organizacja'),
        ),
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 2, 49, 40, 874774, tzinfo=utc), verbose_name='Koniec treningu'),
        ),
        migrations.AlterField(
            model_name='training',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VolleyUp.Organization', verbose_name='Organizacja'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ManyToManyField(related_name='users', to='VolleyUp.Organization', verbose_name='Organizacja'),
        ),
        migrations.CreateModel(
            name='Uprawnienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_uprawnien', models.CharField(max_length=64)),
                ('organization', models.ManyToManyField(related_name='uprawnienia', to='VolleyUp.Organization', verbose_name='Organizacja')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='uprawnienia',
            field=models.ManyToManyField(related_name='users_upr', to='VolleyUp.Uprawnienia', verbose_name='Uprawnienia'),
        ),
    ]
