# Generated by Django 2.2.2 on 2019-06-27 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('VolleyUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 9, 53, 3, 265301, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 8, 23, 3, 265269, tzinfo=utc)),
        ),
    ]
