# Generated by Django 2.2.2 on 2019-06-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolleyUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
